-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         PostgreSQL 11.5, compiled by Visual C++ build 1914, 64-bit
-- SO del servidor:              
-- HeidiSQL Versión:             10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES  */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Volcando estructura para tabla public.comercios
CREATE TABLE IF NOT EXISTS "comercios" (
	com_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"com_nombre" TEXT NOT NULL ,
	"com_direccion" CHARACTER VARYING(64) NULL DEFAULT NULL ,
	"com_descripcion" CHARACTER VARYING(256) NULL DEFAULT NULL ,
	"com_latitud" DOUBLE PRECISION NULL DEFAULT NULL ,
	"com_longitud" DOUBLE PRECISION NULL DEFAULT NULL ,
	"com_estado" INTEGER NULL DEFAULT NULL 
);

-- Volcando datos para la tabla public.comercios: 1 rows
/*!40000 ALTER TABLE "comercios" DISABLE KEYS */;
INSERT INTO "comercios" ( "com_nombre","com_direccion", "com_descripcion", "com_latitud", "com_longitud", "com_estado") VALUES
	( E'Pizzeria',E'sarasa 234', E'Mejor calidad', -54.32, -40.32, 1),
	( E'Heladeria',E'sarasa 114', E'Todos los helados', -54.32, -40.20, 1),
	( E'Comida Japonesa',E'sarasa 484', E'kanji', -54.32, -40.10, 1);
/*!40000 ALTER TABLE "comercios" ENABLE KEYS */;

-- Volcando estructura para tabla public.items
CREATE TABLE IF NOT EXISTS "items" (
	item_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"item_pedidoid" INTEGER NULL DEFAULT NULL ,
	"item_productoid" INTEGER NULL DEFAULT NULL ,
	"item_cantidad" INTEGER NULL DEFAULT NULL ,
	"item_descripcion" CHARACTER VARYING(256) NULL DEFAULT NULL 
);

-- Volcando datos para la tabla public.items: 57 rows
/*!40000 ALTER TABLE "items" DISABLE KEYS */;
INSERT INTO "items" ( "item_pedidoid", "item_productoid", "item_cantidad", "item_descripcion") VALUES
	( 39, 1, 2, NULL),
	( 39, 2, 4, NULL),
	( 39, 3, 3, NULL),
	( 40, 1, 2, NULL),
	( 40, 2, 4, NULL),
	( 40, 3, 3, NULL),
	( 41, 1, 2, NULL),
	( 41, 2, 4, NULL),
	( 41, 3, 3, NULL),
	( 42, 1, 2, NULL),
	( 42, 2, 4, NULL),
	( 42, 3, 3, NULL),
	( 43, 1, 2, NULL),
	( 43, 2, 4, NULL),
	( 43, 3, 3, NULL),
	( 44, 1, 2, NULL),
	( 44, 2, 4, NULL),
	( 44, 3, 3, NULL),
	( 45, 1, 2, NULL),
	( 45, 2, 4, NULL),
	( 45, 3, 3, NULL),
	( 46, 1, 2, NULL),
	( 46, 2, 4, NULL),
	( 46, 3, 3, NULL),
	( 53, 1, 2, NULL),
	( 53, 2, 4, NULL),
	( 53, 3, 3, NULL),
	( 54, 1, 2, NULL),
	( 54, 2, 4, NULL),
	( 54, 3, 3, NULL),
	( 55, 1, 2, NULL),
	( 55, 2, 4, NULL),
	( 55, 3, 3, NULL),
	( 56, 1, 2, NULL),
	( 56, 2, 4, NULL),
	( 56, 3, 3, NULL),
	( 57, 1, 2, NULL),
	( 57, 2, 4, NULL),
	( 57, 3, 3, NULL),
	( 38, 1, 2, NULL),
	( 38, 2, 4, NULL),
	( 38, 3, 3, NULL);
/*!40000 ALTER TABLE "items" ENABLE KEYS */;

-- Volcando estructura para tabla public.pedidos
CREATE TABLE IF NOT EXISTS "pedidos" (
	ped_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"ped_userid" INTEGER NULL DEFAULT NULL ,
	"ped_deliveryid" INTEGER NULL DEFAULT NULL ,
	"ped_total" INTEGER NULL DEFAULT NULL ,
	"ped_envio" INTEGER NULL DEFAULT NULL ,
	"ped_direccioninicio" CHARACTER VARYING(64) NULL DEFAULT NULL ,
	"ped_direcciondestino" CHARACTER VARYING(64) NULL DEFAULT NULL ,
	"ped_latitudinicio" DOUBLE PRECISION NULL DEFAULT NULL ,
	"ped_longitudinicio" DOUBLE PRECISION NULL DEFAULT NULL ,
	"ped_latituddestino" DOUBLE PRECISION NULL DEFAULT NULL ,
	"ped_longituddestino" DOUBLE PRECISION NULL DEFAULT NULL ,
	"ped_descripcion" CHARACTER VARYING(256) NULL DEFAULT NULL ,
	"ped_estado" INTEGER NULL DEFAULT NULL 
);

-- Volcando datos para la tabla public.pedidos: 19 rows
/*!40000 ALTER TABLE "pedidos" DISABLE KEYS */;
INSERT INTO "pedidos" ( "ped_userid", "ped_deliveryid", "ped_total", "ped_envio", "ped_direccioninicio", "ped_direcciondestino", "ped_latitudinicio", "ped_longitudinicio", "ped_latituddestino", "ped_longituddestino", "ped_descripcion", "ped_estado") VALUES
	( 1, 1, 1590, 0, E'sarasa 11 3b', E'paseo colon 11re', -45.1, -50.1, -43.1, -52.1, NULL, 2),
	( 1, 0, 1590, 0, E'sarasa 11 3b', E'paseo colon 11re', -45.1, -50.1, -43.1, -52.1, NULL, 1),
	( 1, 0, 1590, 0, E'sarasa 11 3b', E'paseo colon 11re', -45.1, -50.1, -43.1, -52.1, NULL, 1),
	( 1, 0, 1590, 0, E'sarasa 11 3b', E'paseo colon 11re', -45.1, -50.1, -43.1, -52.1, NULL, 1),
	( 1, 0, 1590, 0, E'sarasa 11 3b', E'paseo colon 11re', -45.1, -50.1, -43.1, -52.1, NULL, 1),
	( 1, 0, 1590, 0, E'sarasa 11 3b', E'paseo colon 11re', -45.1, -50.1, -43.1, -52.1, NULL, 1),
	( 1, 0, 1590, 0, E'sarasa 11 3b', E'paseo colon 11re', -45.1, -50.1, -43.1, -52.1, NULL, 1),
	( 1, 0, 1590, 0, E'sarasa 11 3b', E'paseo colon 11re', -45.1, -50.1, -43.1, -52.1, NULL, 1),
	( 1, 0, 1590, 0, E'sarasa 11 3b', E'paseo colon 11re', -45.1, -50.1, -43.1, -52.1, NULL, 1),
	( 1, 0, 1590, 0, E'sarasa 11 3b', E'paseo colon 11re', -45.1, -50.1, -43.1, -52.1, NULL, 1),
	( 1, 0, 0, 0, E'sarasa 11 3b', E'paseo colon 11re', -45.1, -50.1, -43.1, -52.1, NULL, 1),
	( 1, 0, 0, 0, E'sarasa 11 3b', E'paseo colon 11re', -45.1, -50.1, -43.1, -52.1, NULL, 1),
	( 1, 0, 0, 0, E'sarasa 11 3b', E'paseo colon 11re', -45.1, -50.1, -43.1, -52.1, NULL, 1),
	( 1, 0, 0, 0, E'sarasa 11 3b', E'paseo colon 11re', -45.1, -50.1, -43.1, -52.1, NULL, 1),
	( 1, 0, 0, 0, E'sarasa 11 3b', E'paseo colon 11re', -45.1, -50.1, -43.1, -52.1, NULL, 1),
	( 1, 0, 0, 0, E'sarasa 11 3b', E'paseo colon 11re', -45.1, -50.1, -43.1, -52.1, NULL, 1),
	( 1, 0, 1590, 0, E'sarasa 11 3b', E'paseo colon 11re', -45.1, -50.1, -43.1, -52.1, NULL, 1),
	( 1, 0, 1590, 0, E'sarasa 11 3b', E'paseo colon 11re', -45.1, -50.1, -43.1, -52.1, NULL, 1),
	( 1, 0, 1590, 0, E'sarasa 11 3b', E'paseo colon 11re', -45.1, -50.1, -43.1, -52.1, NULL, 1),
	( 1, 0, 1590, 0, E'sarasa 11 3b', E'paseo colon 11re', -45.1, -50.1, -43.1, -52.1, NULL, 1);
/*!40000 ALTER TABLE "pedidos" ENABLE KEYS */;

-- Volcando estructura para tabla public.productos
CREATE TABLE IF NOT EXISTS "productos" (
	prod_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"prod_value" INTEGER NULL DEFAULT NULL ,
	"prod_nombre" CHARACTER VARYING(32) NULL DEFAULT NULL ,
	"prod_idcomercio" INTEGER NULL DEFAULT NULL ,
	"prod_descripcion" CHARACTER VARYING(256) NULL DEFAULT NULL 
);

-- Volcando datos para la tabla public.productos: 3 rows
/*!40000 ALTER TABLE "productos" DISABLE KEYS */;
INSERT INTO "productos" ( "prod_value", "prod_nombre", "prod_idcomercio", "prod_descripcion") VALUES
	( 350, E'combo1', 1, E'papas fritas, hamburquesa de soja'),
	( 200, E'combo2', 1, E'milanesa soja'),
	( 30, E'combo4', 1, E'agua');
/*!40000 ALTER TABLE "productos" ENABLE KEYS */;

-- Volcando estructura para tabla public.users
CREATE TABLE IF NOT EXISTS "users" (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"nombre" TEXT NOT NULL ,
	"pass" TEXT NOT NULL ,
	"mail" TEXT NOT NULL ,
	"rol" INTEGER NULL DEFAULT NULL ,
	"puntaje" INTEGER NULL DEFAULT NULL ,
	"nivel" INTEGER NULL DEFAULT NULL ,
	"foto" TEXT NOT NULL ,
	"cantEnvios" INTEGER NULL DEFAULT NULL,
	"redsocial" TEXT NOT NULL ,
	"uidfirebase" TEXT NOT NULL
);
 

/*Id , nombre , mail ,pass , rol , puntaje,nivel,fotoy cantidad de envios*/ 
-- Volcando datosd para la tabla public.users: 2 rows 
/*!40000 ALTER TABLE "users" DISABLE KEYS */;
INSERT INTO "users" ( "nombre", "pass", "mail","rol","puntaje","nivel","foto","cantEnvios","redsocial","uidfirebase") VALUES
	( E'josue', E'contra', E'josue@',1,1,1,E'foto1.png',0,E'ninguna',E'-1'),
	( E'diegov', E'contra', E'dieg@',1,1,1,E'foto2.png',0,E'ninguna',E'-1');
/*!40000 ALTER TABLE "users" ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT   */;
/*DELETE FROM users WHERE id = 3*/;


CREATE TABLE IF NOT EXISTS "parametros" (
	par_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"par_nombre" TEXT NOT NULL,
	"par_value" TEXT NOT NULL ,
);
INSERT INTO "parametros" ( "par_nombre", "par_value") VALUES
	( E'pesos_km', E'10'),
    ( E'maxkms', E'20');

